import * as THREE from 'three';
import { MoodConfig } from '../types';

export const moodStyles: Record<string, MoodConfig> = {
  Harmonisch: {
    name: 'Harmonisch',
    skyColor: '#87CEEB',
    fog: { color: '#87CEEB', density: 0.001 },
    ambient: { color: '#ffffff', intensity: 0.8 },
    keyLight: {
      color: '#FFDDAA',
      intensity: 3,
      position: [100, 150, 50],
    },
    sun: { visible: true, color: '#FFFFAA' },
    groundColor: '#7CFC00',
    vegetation: {
      treeColor: '#228B22',
      cropColor: '#ADFF2F',
    },
    bloom: {
      threshold: 0.85,
      strength: 0.8,
      radius: 0.5,
    },
    particles: {
      count: 200,
      material: {
        size: 2,
        textureType: 'sparkle',
        blending: 'additive',
        depthWrite: false,
        opacity: 0.8,
        color: '#FFFFDD',
      },
      behavior: {
        spawnArea: [800, 200, 800],
        velocity: [0, 0.1, 0],
        direction: 'up',
      },
    },
    ui: {
      borderColor: '#FFFFAA',
      shadowColor: '#FFFF00',
      shadowBlur: '30',
    },
  },
  Kooperativ: {
    name: 'Kooperativ',
    skyColor: '#220033',
    fog: { color: '#220033', density: 0.002 },
    ambient: { color: '#ffffff', intensity: 0.6 },
    keyLight: {
      color: '#FFD700',
      intensity: 3,
      position: [-150, 80, 0],
    },
    sun: { visible: true, color: '#FFD700' },
    groundColor: '#4B0082',
    vegetation: {
      pulsingColor: true,
      treeColor: '#ff00ff',
      cropColor: '#00ffff',
    },
    bloom: {
      threshold: 0.1,
      strength: 3.0,
      radius: 1.0,
    },
    particles: {
      count: 5000,
      material: {
        size: 1.5,
        textureType: 'sparkle',
        blending: 'additive',
        depthWrite: false,
        opacity: 1.0,
        color: 'rainbow',
      },
      behavior: {
        spawnArea: [800, 200, 800],
        velocity: [0, 0.05, 0],
        direction: 'up',
      },
    },
    dynamicLights: Array.from({ length: 8 }, (_, i) => ({
      name: `dynamic_spot_${i}`,
      type: 'spot' as const,
      color: new THREE.Color().setHSL(i / 8, 1, 0.5).getHex(),
      intensity: 200,
      angle: Math.PI / 8,
      penumbra: 0.5,
      decay: 2,
      position: [0, 80, 0],
    })),
    ui: {
      borderColor: 'rainbow',
      shadowColor: 'rainbow',
      shadowBlur: '40',
    },
  },
  Neutral: {
    name: 'Neutral',
    skyColor: '#B0C4DE',
    fog: { color: '#B0C4DE', density: 0.002 },
    ambient: { color: '#aaaaaa', intensity: 1.0 },
    keyLight: {
      color: '#ffffff',
      intensity: 2.5,
      position: [50, 100, 50],
    },
    sun: { visible: true, color: '#FFFFFF' },
    groundColor: '#8FBC8F',
    vegetation: {
      treeColor: '#556B2F',
      cropColor: '#6B8E23',
    },
    bloom: {
      threshold: 0.9,
      strength: 0.5,
      radius: 0.5,
    },
    ui: {
      borderColor: '#CCCCCC',
      shadowColor: '#FFFFFF',
      shadowBlur: '20',
    },
  },
  Distanziert: {
    name: 'Distanziert',
    skyColor: '#483D8B',
    fog: { color: '#483D8B', density: 0.003 },
    ambient: { color: '#483D8B', intensity: 0.7 },
    keyLight: {
      color: '#ffccaa',
      intensity: 4,
      position: [-200, 50, 0],
    },
    sun: { visible: true, color: '#ffccaa' },
    groundColor: '#4A442D',
    vegetation: {
      treeColor: '#2F4F4F',
      cropColor: '#556B2F',
    },
    bloom: {
      threshold: 0.5,
      strength: 1.2,
      radius: 0.8,
    },
    particles: {
      count: 3000,
      material: {
        size: 0.5,
        textureType: 'sparkle',
        blending: 'normal',
        depthWrite: true,
        opacity: 0.5,
        color: '#AAAAFF',
      },
      behavior: {
        spawnArea: [800, 200, 800],
        velocity: [0, -2, 0],
        direction: 'down',
      },
    },
    ui: {
      borderColor: '#ffccaa',
      shadowColor: '#FF4500',
      shadowBlur: '35',
    },
  },
  Spannung: {
    name: 'Spannung',
    skyColor: '#200000',
    fog: { color: '#200000', density: 0.009 },
    ambient: { color: '#400000', intensity: 0.8 },
    keyLight: {
      color: '#ff0000',
      intensity: 0,
      position: [0, 100, 0],
    },
    sun: { visible: false, color: '#ff0000' },
    groundColor: '#1a0000',
    vegetation: {
      treeColor: '#1a0000',
      cropColor: '#100000',
      emissiveGlow: true,
      emissiveColor: '#ff4500',
    },
    bloom: {
      threshold: 0.1,
      strength: 2.0,
      radius: 1.2,
    },
    particles: {
      count: 500,
      material: {
        size: 1,
        textureType: 'sparkle',
        blending: 'additive',
        depthWrite: false,
        opacity: 0.9,
        color: '#FF4500',
      },
      behavior: {
        spawnArea: [800, 200, 800],
        velocity: [0, 0.2, 0],
        direction: 'up',
      },
    },
    ui: {
      borderColor: '#FF4500',
      shadowColor: '#FF0000',
      shadowBlur: '40',
    },
  },
  Konflikt: {
    name: 'Konflikt',
    skyColor: '#050505',
    fog: { color: '#110000', density: 0.005 },
    ambient: { color: '#220000', intensity: 1.5 },
    keyLight: {
      color: '#ffffff',
      intensity: 0,
      position: [0, 100, 0],
    },
    sun: { visible: false, color: '#ffffff' },
    groundColor: '#333333',
    vegetation: {
      treeColor: '#444444',
      cropColor: '#555555',
    },
    bloom: { threshold: 0, strength: 3.0, radius: 0.8 },
    dynamicLights: [
      {
        name: 'dynamic_strobe',
        type: 'spot' as const,
        color: 0xffffff,
        intensity: 0,
        angle: Math.PI / 3,
        penumbra: 0,
        decay: 1,
        position: [0, 150, 0],
      },
    ],
    ui: {
      borderColor: '#FFFFFF',
      shadowColor: '#FF0000',
      shadowBlur: '50',
    },
  },
  Krieg: {
    name: 'Krieg',
    skyColor: '#050000',
    fog: { color: '#000000', density: 0.01 },
    ambient: { color: '#110000', intensity: 1.2 },
    keyLight: {
      color: '#ff0000',
      intensity: 0,
      position: [0, 100, 0],
    },
    sun: { visible: false, color: '#ff0000' },
    groundColor: '#080000',
    vegetation: {
      treeColor: '#050000',
      cropColor: '#030000',
      emissiveGlow: true,
      emissiveColor: '#ff0000',
    },
    bloom: { threshold: 0, strength: 2.2, radius: 1.5 },
    particles: [
      {
        name: 'smoke',
        count: 2000,
        material: {
          size: 30,
          textureType: 'smoke' as const,
          blending: 'normal' as const,
          depthWrite: false,
          opacity: 0.4,
          color: '#111111',
        },
        behavior: {
          spawnArea: [800, 250, 800],
          velocity: [0.05, 0.1, 0.05],
          direction: 'up' as const,
        },
      },
      {
        name: 'fire',
        count: 1000,
        material: {
          size: 1.5,
          textureType: 'sparkle' as const,
          blending: 'additive' as const,
          depthWrite: false,
          opacity: 0.9,
          color: '#FF4500',
        },
        behavior: {
          spawnArea: [800, 100, 800],
          velocity: [0, 0.4, 0],
          direction: 'up' as const,
        },
      },
    ],
    dynamicLights: [
      {
        name: 'dynamic_explosion_main',
        type: 'point' as const,
        color: 0xff8c00,
        intensity: 0,
        distance: 600,
        decay: 2,
        position: [0, 50, 0],
      },
      {
        name: 'dynamic_explosion_flash',
        type: 'point' as const,
        color: 0xffffff,
        intensity: 0,
        distance: 400,
        decay: 1.5,
        position: [0, 50, 0],
      },
      {
        name: 'dynamic_strobe',
        type: 'spot' as const,
        color: 0xff0000,
        intensity: 0,
        angle: Math.PI / 2,
        penumbra: 0.5,
        decay: 1,
        position: [0, 200, 0],
      },
    ],
    ui: {
      borderColor: '#8B0000',
      shadowColor: '#FF0000',
      shadowBlur: '60',
    },
  },
  Groove: {
    name: 'Groove',
    skyColor: '#2d1b69',
    fog: { color: '#2d1b69', density: 0.0025 },
    ambient: { color: '#ffd700', intensity: 0.7 },
    keyLight: {
      color: '#ffd700',
      intensity: 4.0,
      position: [0, 120, 100],
    },
    sun: { visible: true, color: '#ffd700' },
    groundColor: '#4a0080',
    vegetation: {
      treeColor: '#8a2be2',
      cropColor: '#ffd700',
      pulsingColor: true,
    },
    bloom: {
      threshold: 0.4,
      strength: 2.2,
      radius: 0.9,
    },
    particles: {
      count: 3000,
      material: {
        size: 2.5,
        textureType: 'sparkle',
        blending: 'additive',
        depthWrite: false,
        opacity: 0.8,
        color: '#ffd700',
      },
      behavior: {
        spawnArea: [600, 150, 600],
        velocity: [0, 0.08, 0],
        direction: 'up',
      },
    },
    dynamicLights: [
      {
        name: 'groove_spot_1',
        type: 'spot' as const,
        color: 0xffd700,
        intensity: 150,
        angle: Math.PI / 6,
        penumbra: 0.3,
        decay: 1.8,
        position: [-100, 80, 50],
      },
      {
        name: 'groove_spot_2',
        type: 'spot' as const,
        color: 0x8a2be2,
        intensity: 150,
        angle: Math.PI / 6,
        penumbra: 0.3,
        decay: 1.8,
        position: [100, 80, -50],
      },
    ],
    ui: {
      borderColor: '#ffd700',
      shadowColor: '#8a2be2',
      shadowBlur: '35',
    },
  },
  Transzendent: {
    name: 'Transzendent',
    skyColor: '#1a1a2e',
    fog: { color: '#16213e', density: 0.004 },
    ambient: { color: '#4a5568', intensity: 0.9 },
    keyLight: {
      color: '#00ffff',
      intensity: 2.0,
      position: [0, 200, 0],
    },
    sun: { visible: true, color: '#00ffff' },
    groundColor: '#2d3748',
    vegetation: {
      treeColor: '#4a5568',
      cropColor: '#718096',
      emissiveGlow: true,
      emissiveColor: '#00ffff',
    },
    bloom: {
      threshold: 0.3,
      strength: 1.8,
      radius: 1.2,
    },
    particles: {
      count: 1000,
      material: {
        size: 1,
        textureType: 'sparkle',
        blending: 'additive',
        depthWrite: false,
        opacity: 0.6,
        color: '#00ffff',
      },
      behavior: {
        spawnArea: [600, 300, 600],
        velocity: [0, 0.03, 0],
        direction: 'up',
      },
    },
    ui: {
      borderColor: '#00ffff',
      shadowColor: '#4fd1c7',
      shadowBlur: '25',
    },
  },
};
